version: "3.8"

services:
  reid-pipeline:
    image: nvcr.io/nvidia/deepstream:7.0-triton-multiarch
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /app
    network_mode: host
    command: python3 pipeline.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]